name: Tests

on:
    push:
        paths-ignore:
            - '**.md'
    pull_request:
        paths-ignore:
            - '**.md'

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: [8.1]
                laravel: [9.*]
                stability: [prefer-lowest, prefer-stable]
                include:
                    -   laravel: 9.*
                        testbench: 7.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
                with:
                    fetch-depth: 2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.stability }} --prefer-dist --no-interaction

            -   name: Execute tests
                run: vendor/bin/pest -p
